version: '3'
services:
  go2rtc:
    image: alexxit/go2rtc
    container_name: go2rtc
    ports:
      - "1984:1984"
      - "8555:8555"
      - "8554:8554"
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml
    restart: unless-stopped